### ISSUE TITLE
Sections missing?

### ISSUE THREAD

**Issue by mickeypash** [aws-iot-builder-tools/iot-provisioning-secretfree#5]
These sections are mentioned in the table of contents but do not appear in the body of the README?

System Components
- IoT Device
- API Gateway

**Comment by rpcme** [comment]
Hello @mickeypash - an oversight. They are defined in the cloudformation.  Were you more looking for configuration details or runtime behavior details?  I can prioritize this in my task list.

**Comment by mickeypash** [comment]
Hey Richard!

**Comment by rpcme** [comment]
Ok.  I will schedule myself to work on this...

**Comment by rpcme** [comment]
I believe this was resolved when I refactored the documentation.
