### ISSUE TITLE
iotcore Lambda Key Errors: Possibly related to incomplete instructions for POST "body"

### ISSUE THREAD

**Issue by plentyofbytes** [aws-iot-builder-tools/iot-provisioning-secretfree#6]
I have stumbled across several problems with this GitHub and solved them all until I got to the iotcore lambda which is used by the /proto method. I am getting Key-errors which are due to the table and keys in the Lambda not being found in dynamodb. I am wondering if this has to do with the POST Request Body. 

There is a section in the README that says:

"
Next, we enter the Request body. It will look something like this. Note that the format is RAW and set to application/json.

Next, enter the request URL. Get this from your deployed API in the stage Live.
"

When it says "should look like this.", **there is actually nothing displayed for us to observe**. I am unsure if there really should be a body or not. What makes me think there should be a body is the code for the lambda:

```
  s3_bucket = response['Item']['pubkey-bucket']['S']
    s3_object = response['Item']['pubkey-object']['S']
    content_object = s3.Object(s3_bucket, s3_object)
    file_content = content_object.get()['Body'].read().decode('utf-8')
```

Specifically, what makes me ask about the POST body is the last line above where it calls get() and looks for 'Body'. 

Furthermore, it seems there is supposed to be a table called 'widgiot-public-keys', but there isn't one. Also, it is looking for items called 'pubkey-bucket' and 'pubkey-object', but of course those don't exist either.

I understand sending the header device-csr to the /proto API URL, but I don't understand where this table with these items is supposed to come from.

The entire Function inside the Lambda is:
```
def get_pubkey( req ):
    device_id = req.get_subject().CN

    d = boto3.client('dynamodb')
    s3 = boto3.resource('s3')
    
    response = d.get_item(
        Key={ 'device-id': { 'S' : device_id } },
        TableName= 'widgiot-public-keys' 
    )
    
    s3_bucket = response['Item']['pubkey-bucket']['S']
    s3_object = response['Item']['pubkey-object']['S']
    content_object = s3.Object(s3_bucket, s3_object)
    file_content = content_object.get()['Body'].read().decode('utf-8')

    return file_content
```

Can someone please explain the missing table, and if it has anything to do with the POST Body?
Thank you

**Comment by rpcme** [comment]
Also if you could kindly let me know what else you fixed, or if you would like to do a pull request, I will include those.

Thank you so much.

**Comment by MicroTechEE** [comment]
Thank you for the quick response. I understand that tech moves fast, and I also understand that this project is a lot to keep up with.

Thank you for confirming that we do not have to include a **Body in the POST** request.

I will do my best to sum up a list of what I have changed. I know I had to work on the iotcore lambda permissions, but you would likely solve it better than I did. I'll add this later, after this comment.

I can confirm that my table name is ${SKUNAME}-iotprovisioning-secretfree, with SKUNAME being the first argument passed in ./build-and-upload.sh.

I tried changing that in the lambda, but more things than that were incorrect for my situation, so I did not succeed overall. It seems, even with the correct table name, I still do not understand how to proceed with the key names. I understand most of what is going on, but I am still new to AWS and although I have made great leaps in my understanding lately, I still have some learning to do (I'm mainly an embedded firmware engineer).

I wanted to add that TI is linking to this GitHub, which is how I got here. They are including this in their[ "AWS Provisioning" ](https://dev.ti.com/tirex/explore/content/simplelink_academy_awsplugin_3_40_01_00/modules/sdk_plugins/cc32xx_aws_plugin_provisioning/cc32xx_aws_plugin_provisioning.html)Academy page for provisioning the CC3235S. You might see an increase in traffic to this project as the months and years pass. I'm willing to help with it if I can.  

As you can see, I don't have any credit on GitHub. I don't mind doing a pull request, but I don't know exactly how that all works. At the very least, I will make a list of things I've done on my own, so others can benefit. Please PM me if needed also, thank you.
